CREATE USER sa IDENTIFIED BY "23"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER sa QUOTA UNLIMITED ON USERS;
GRANT "CONNECT" TO sa;
GRANT "RESOURCE" TO sa;
GRANT CREATE ANY VIEW TO sa;



CREATE TABLE FILENAMES 
(FILENAME VARCHAR2(100 BYTE));


CREATE SEQUENCE PROD_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999;
CREATE SEQUENCE card_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999;
CREATE SEQUENCE cust_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999;


CREATE TABLE CE_CUSTOMERS 
(
  CUSTOMER_SURR_ID NUMBER(*, 0)
, ID NUMBER(*, 0) 
, NAME VARCHAR2(100 BYTE) 
, USERNAME VARCHAR2(100 BYTE) 
, EMAIL VARCHAR2(100 BYTE) 
, DATEOFBIRTH DATE 
, STREETADDRESS VARCHAR2(150 BYTE) 
, CITY VARCHAR2(100 BYTE) 
, COUNTRY VARCHAR2(100 BYTE) 
, ZIP VARCHAR2(20 BYTE) 
, STATE VARCHAR2(5 BYTE) 
, PHONE VARCHAR2(20 BYTE) 
, CONSTRAINT CE_CUSTOMERS_PK PRIMARY KEY (CUSTOMER_SURR_ID )ENABLE) 
;



CREATE TABLE DIM_CUSTOMERS 
(
  CUSTOMER_SURR_ID NUMBER(*, 0)
, ID NUMBER(*, 0) 
, NAME VARCHAR2(100 BYTE) 
, USERNAME VARCHAR2(100 BYTE) 
, EMAIL VARCHAR2(100 BYTE) 
, DATEOFBIRTH DATE 
, STREETADDRESS VARCHAR2(150 BYTE) 
, CITY VARCHAR2(100 BYTE) 
, COUNTRY VARCHAR2(100 BYTE) 
, ZIP VARCHAR2(20 BYTE) 
, STATE VARCHAR2(5 BYTE) 
, PHONE VARCHAR2(20 BYTE) 
, CONSTRAINT DIM_CUSTOMERS_PK PRIMARY KEY (CUSTOMER_SURR_ID )ENABLE) 
;




CREATE TABLE CE_PRODUCTS 
(SURR_ID NUMBER (*,0)
,  PRODUCTS NUMBER(*, 0) 
, PRODUCTNAME VARCHAR2(200 BYTE) 
, COMPANYNAME VARCHAR2(200 BYTE) 
, PRICE FLOAT(126) 
, WAREHOUSELOCATIONSTATE VARCHAR2(5 BYTE) 
, CONSTRAINT CE_PRODUCTS_PK PRIMARY KEY(SURR_ID)ENABLE);


CREATE TABLE DIM_PRODUCTS 
(SURR_ID NUMBER (*,0)
,  PRODUCTS NUMBER(*, 0) 
, PRODUCTNAME VARCHAR2(200 BYTE) 
, COMPANYNAME VARCHAR2(200 BYTE) 
, PRICE FLOAT(126) 
, WAREHOUSELOCATIONSTATE VARCHAR2(5 BYTE) 
, CONSTRAINT DIM_PRODUCTS_PK PRIMARY KEY(SURR_ID)ENABLE);



 CREATE TABLE CE_CARDS 
(
  
  CARD_SURR_ID NUMBER,
  CREDITCARD VARCHAR2(100 BYTE), 
  CREDITCARDNUMBER VARCHAR2(100 BYTE), 
  CONSTRAINT CE_CARDS_PK PRIMARY KEY (CARD_SURR_ID)ENABLE);
  
  
   CREATE TABLE DIM_CARDS 
(
  
  CARD_SURR_ID NUMBER,
  CREDITCARD VARCHAR2(100 BYTE), 
  CREDITCARDNUMBER VARCHAR2(100 BYTE), 
  CONSTRAINT DIM_CARDS_PK PRIMARY KEY (CARD_SURR_ID)ENABLE);
  
  
  CREATE TABLE src_CARDS 
(CREDITCARD VARCHAR2(100 BYTE), 
  CREDITCARDNUMBER VARCHAR2(100 BYTE));

  
CREATE TABLE CE_PURCHASE 
(
  PAYMENTID NUMBER(*, 0) 
, CUSTOMERID NUMBER(*, 0) 
, PRODUCTID NUMBER(*, 0) 
, TRANSACTIONDATE DATE 
, CARDID NUMBER(*, 0) 
, ISINTERSTATE VARCHAR2(1 BYTE) 
) ;  
    
CREATE TABLE FCT_PURCHASE 
(
  PAYMENTID NUMBER(*, 0) 
, CUSTOMERID NUMBER(*, 0) 
, PRODUCTID NUMBER(*, 0) 
, TRANSACTIONDATE DATE 
, CARDID NUMBER(*, 0) 
, ISINTERSTATE VARCHAR2(1 BYTE) 
) ;  
    
