CREATE USER sa IDENTIFIED BY "23"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER sa QUOTA UNLIMITED ON USERS;
GRANT "CONNECT" TO sa;
GRANT "RESOURCE" TO sa;
GRANT CREATE ANY VIEW TO sa;




CREATE TABLE FILENAMES 
(FILENAME VARCHAR2(100 BYTE));